In [2]:
import numpy as np
from math import sqrt

In [3]:
#Gauss Seidel

def Gauss_Seidel(A,e):
    n = len(A)
    x0 = np.zeros(n)
    x_temp = np.zeros(n)
    x1 = np.zeros(n)
    count = 0

    condition = True
    while condition:
        for i in range(0,n):
            x0 = np.copy(x1)
            x1[i] = np.around( (A[i,len(A)] - ( np.sum(np.around(A[i,:-1]*x1,5)) - np.around((A[i,i]*x1[i]),5) ))/(A[i,i]),5)
            x_temp = abs(x1 - x0)
        count += 1
        print(x1)
        # condition = (tolerance condidtion)
        condition =  count <= 10

In [4]:
# Gauss Jacobi

def Gauss_Jacobi(A,e):
    n = len(A)
    x0 = np.zeros(n)
    x_temp = np.zeros(n)
    x1 = np.zeros(n)
    #e = 0.001
    count = 0

    condition = True
    while condition:
        x0 = np.copy(x1)
        for i in range(0,n):
            x1[i] = np.around( (A[i,len(A)] - ( np.sum(np.around(A[i,:-1]*x0,5)) - np.around((A[i,i]*x0[i]),5) ))/(A[i,i]),5)
        x_temp = abs(x1 - x0)
        count += 1
        print(x1)
        condition = count <= 10

In [5]:
#A = np.around(np.array(np.random.rand(3*4),dtype=float),decimals = 5).reshape(3,4)
A = A = np.array([[-10,22,-37,35,6],[-3,43,40,41,-42],[-35,37,12,-49,-23],[22,0,-38,-48,43]],dtype=float)
tolerance = 0.1
print(A)

[[-10.  22. -37.  35.   6.]
 [ -3.  43.  40.  41. -42.]
 [-35.  37.  12. -49. -23.]
 [ 22.   0. -38. -48.  43.]]


In [6]:
print("-----Jacobi--------")
Gauss_Jacobi(A,tolerance)

-----Jacobi--------
[-0.6     -0.97674 -1.91667 -0.89583]
[ 1.20745  1.61851 -4.31302  0.34653]
[20.13175  2.7892  -1.97035  3.07206]
[23.57874 -0.66849 60.74515  9.89108]
[-192.20895  -65.26986  109.30441  -38.17882]
[-682.24588  -79.66213 -517.17422 -175.52426]
[ 1123.35302   599.87734 -2462.89964    95.83773]
[10767.29087  2277.08599  1816.24524  2463.76985]
[ 6912.07626 -3288.47676 34442.06012  3496.25167]
[-122433.99047  -34891.49987   44574.13675  -24099.49181]
[-326034.42702  -27028.6111  -347925.18916  -91404.33306]


In [7]:
print("-----Seidel--------")
Gauss_Seidel(A,tolerance)

-----Seidel--------
[-0.6     -1.0186  -0.52598 -0.75443]
[-3.535300e+00 -1.477000e-02 -1.526301e+01  9.567040e+00]
[  89.32528   10.33134  265.82585 -170.40054]
[-1557.82859  -194.46739 -4641.77781  2959.84016]
[ 27105.5902    3385.87061  80702.30102 -51466.82197]
[ -471284.07533   -58880.1527  -1403189.52193   894852.2745 ]
[  8194247.25595   1023752.03234  24397297.26768 -15558831.24044]
[-1.42473655e+08 -1.78000190e+07 -4.24196666e+08  2.70521934e+08]
[ 2.47719439e+09  3.09489546e+08  7.37552210e+09 -4.70357423e+09]
[-4.30710646e+10 -5.38110545e+09 -1.28238458e+11  8.17812080e+10]
[ 7.48878091e+11  9.35614666e+10  2.22968651e+12 -1.42193269e+12]
